server:
  port: 8080
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:todolist # h2 database 連接位址
    driver-class-name: org.h2.Driver # 配置driver
    username: sa # database 用戶名
    password: # database 密碼

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  thymeleaf:
    cache: false
    prefix: classpath:/templates/ # 設定去templates資料夾找html檔案
    suffix: .html
    encoding: UTF-8
    mode: HTML5
